// Common game terms with their explanations
export const gameTerms: Record<string, string> = {
  'ability-score': 'The six primary attributes that define a character\'s physical and mental capabilities: Strength, Dexterity, Constitution, Intelligence, Wisdom, and Charisma.',
  'modifier': 'A number derived from an ability score, calculated as (score - 10) / 2, rounded down. Used for most d20 rolls.',
  'proficiency-bonus': 'A bonus that increases with character level, added to rolls you\'re proficient in. Starts at +2 and increases every 4 levels.',
  'advantage': 'Roll two d20s and use the higher result. Given by favorable circumstances.',
  'disadvantage': 'Roll two d20s and use the lower result. Given by unfavorable circumstances.',
  'dc': 'Difficulty Class - the target number you need to meet or exceed on a d20 roll to succeed.',
  'ac': 'Armor Class - how hard you are to hit. Attackers must roll this number or higher to hit you.',
  'hit-points': 'Your character\'s health. When reduced to 0, you fall unconscious.',
  'hit-dice': 'Dice used to determine hit points and recover health during short rests.',
  'saving-throw': 'A d20 roll to resist or avoid a harmful effect. Add ability modifier and proficiency bonus if proficient.',
  'skill-check': 'A d20 roll to accomplish a task. Add relevant ability modifier and proficiency bonus if proficient.',
  'attack-roll': 'A d20 roll to hit with an attack. Add ability modifier and proficiency bonus if proficient with the weapon.',
  'damage-roll': 'Roll damage dice and add relevant modifiers when an attack hits.',
  'initiative': 'A Dexterity check that determines turn order in combat. Roll at the start of combat.',
  'action': 'Your main activity on your turn in combat: attack, cast a spell, dash, etc.',
  'bonus-action': 'A secondary, quicker activity some features grant on your turn.',
  'reaction': 'A special action taken in response to a trigger, even on someone else\'s turn.',
  'concentration': 'Maintaining focus on a spell. Can only concentrate on one spell at a time.',
  'spell-slot': 'A resource expended to cast spells. Higher level slots can cast more powerful versions of spells.',
  'cantrip': 'A simple spell that can be cast unlimited times without using spell slots.',
  'short-rest': 'A 1-hour rest to catch your breath, spend Hit Dice to heal, and recover some abilities.',
  'long-rest': 'An 8-hour rest to fully heal, recover all Hit Dice (up to half total), and regain spell slots.',
  'inspiration': 'A reward for good roleplaying that lets you gain advantage on one roll.',
  'death-saves': 'Special saving throws made when at 0 hit points. Three successes stabilize you, three failures mean death.',
};